name = "Create SMP v6"
author = "JustAbigail"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05a4ad8509fdaa113f3642540f893ca91cefe1e832dca1939cd9ea08fcc99469"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
