name = "Create SMP v6"
author = "JustAbigail"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63a505292b47d392e502115e54ae442438729f54ce565895d065aeed6661a192"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
