name = "Create SMP v6"
author = "JustAbigail"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d384bdebdfe85dc031adf06779df4683c65cc9148a9ff6b1cc09e0fd0a447a6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
