export * as lwjgl from "@package/org/lwjgl";
export * as slf4j from "@package/org/slf4j";
export * as joml from "@package/org/joml";
export * as betterx from "@package/org/betterx";
export * as apache from "@package/org/apache";
export * as embeddedt from "@package/org/embeddedt";
export * as sinytra from "@package/org/sinytra";
export * as spongepowered from "@package/org/spongepowered";
export * as objectweb from "@package/org/objectweb";
