import { $CommandList, $MultiDrawBatch } from "@package/net/caffeinemc/mods/sodium/client/gl/device";
import { $RenderSection } from "@package/net/caffeinemc/mods/sodium/client/render/chunk";
import { $ShadowRenderRegion } from "@package/net/irisshaders/iris/mixinterface";
import { $SectionRenderDataStorage } from "@package/net/caffeinemc/mods/sodium/client/render/chunk/data";
import { $ChunkRenderList } from "@package/net/caffeinemc/mods/sodium/client/render/chunk/lists";
import { $StagingBuffer } from "@package/net/caffeinemc/mods/sodium/client/gl/arena/staging";
import { $TerrainRenderPass } from "@package/net/caffeinemc/mods/sodium/client/render/chunk/terrain";
import { $RenderRegionExtension } from "@package/foundry/veil/forge/ext";

declare module "@package/net/caffeinemc/mods/sodium/client/render/chunk/region" {
    export class $RenderRegion implements $ShadowRenderRegion, $RenderRegionExtension {
        removeSection(arg0: $RenderSection): void;
        getChunkX(): number;
        getChunkZ(): number;
        getRenderList(): $ChunkRenderList;
        getOriginY(): number;
        getOriginZ(): number;
        getOriginX(): number;
        veil$getPerspectiveRenderList(): $ChunkRenderList;
        clearAllCachedBatches(): void;
        clearCachedBatchFor(arg0: $TerrainRenderPass): void;
        getCachedBatch(arg0: $TerrainRenderPass): $MultiDrawBatch;
        refreshTesselation(arg0: $CommandList): void;
        refreshIndexedTesselation(arg0: $CommandList): void;
        getFillFractionInv(): number;
        iris$forceClearAllBatches(): void;
        getChunkY(): number;
        swapToRegularRenderList(): void;
        swapToShadowRenderList(): void;
        createStorage(arg0: $TerrainRenderPass): $SectionRenderDataStorage;
        getY(): number;
        getSection(arg0: number): $RenderSection;
        getStorage(arg0: $TerrainRenderPass): $SectionRenderDataStorage;
        createResources(arg0: $CommandList): $RenderRegion$DeviceResources;
        addSection(arg0: $RenderSection): void;
        update(arg0: $CommandList): void;
        isEmpty(): boolean;
        getResources(): $RenderRegion$DeviceResources;
        static key(arg0: number, arg1: number, arg2: number): number;
        "delete"(arg0: $CommandList): void;
        getX(): number;
        getZ(): number;
        static SECTION_INDEX_COUNT_ESTIMATE: number;
        static REGION_WIDTH: number;
        static REGION_HEIGHT_M: number;
        static REGION_WIDTH_SH: number;
        static REGION_LENGTH_M: number;
        static REGION_SIZE: number;
        static SECTION_BUFFER_ESTIMATE: number;
        static SECTION_VERTEX_COUNT_ESTIMATE: number;
        static REGION_LENGTH: number;
        static REGION_LENGTH_SH: number;
        static REGION_WIDTH_M: number;
        static REGION_HEIGHT_SH: number;
        static REGION_HEIGHT: number;
        constructor(arg0: number, arg1: number, arg2: number, arg3: $StagingBuffer);
        get chunkX(): number;
        get chunkZ(): number;
        get renderList(): $ChunkRenderList;
        get originY(): number;
        get originZ(): number;
        get originX(): number;
        get fillFractionInv(): number;
        get chunkY(): number;
        get y(): number;
        get empty(): boolean;
        get resources(): $RenderRegion$DeviceResources;
        get x(): number;
        get z(): number;
    }
}
